name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: repo ref
        type: string

jobs:
  build-and-publish:
    if: github.repository_owner == 'privacyportal' && github.ref == 'refs/heads/production' && github.event.repository.name == 'privacy-kit'
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      # we take the exact client version from the workflow input
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.inputs.ref }}"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npm test

      - run: npm run build

      - name: Update README with SRI Hash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          MAJOR_VERSION=$(echo "$VERSION" | cut -d'.' -f1)
          HASH=$(openssl dgst -sha384 -binary dist/privacy-kit.umd.js | openssl base64 -A)
          sed -i -r "s|@privacy-kit@[0-9]+[.][0-9]+[.][0-9]+/|@privacy-kit@$VERSION/|g" README.md
          sed -i -r "s|@privacy-kit@[0-9]+/|@privacy-kit@$MAJOR_VERSION/|g" README.md
          sed -i -r "s|sha384-[A-Za-z0-9+/=]*|sha384-$HASH|g" README.md

      - name: "Push README changes"
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          file_pattern: "README.md"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "docs: Update CDN to ${{ github.ref_name }} and SRI hash"

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
